### ISSUE TITLE
Pull Request Branches Single view

### ISSUE THREAD

**Issue by marcellodesales** [jenkinsci-transfer/multi-branch-project-plugin#109]
Hi there,

Have you thought about integrating this with the Pull Request Builder for GitHub??? I was thinking if this plugin could set a single branch called "pr" or "pull requests", that would be great to give users the view of the Pull Requests built for the job...

https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin
Branch: `+refs/pull/*:refs/remotes/origin/pr/*`

This is one of the most exciting plugins in a long time!!! Thanks a lot!!!

Marcello

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32238
