### ISSUE TITLE
Required tests don't play nicely with multi-branch-project-plugin

### ISSUE THREAD

**Issue by nschloe** [jenkinsci-transfer/multi-branch-project-plugin#115]
Reporting build statuses back to GitHub works fine for the multi-branch-project-plugin. We'd like to make use of it for GitHub's protected branches: Here, you require a specific test to pass before you can merge a PR into the protected branch. Which tests need passing is configurable, and with the multi-branch-project-plugin, I'm presented with all branches from the past:
![sc2](https://cloud.githubusercontent.com/assets/181628/10700735/175ca14c-79c0-11e5-9adf-050d7f647f25.png)
This isn't useful as a general configuration option, of course. Unfortunately, with multi-branch-project-plugin there's no general `frontend-dev` target (in the above example) that returns anything useful.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32236
