### ISSUE TITLE
Git SCM web hook not triggering builds for branches that contain a forward slash '/'

### ISSUE THREAD

**Issue by jpeletier** [jenkinsci-transfer/multi-branch-project-plugin#117]
Hi,

First of all, thank you for this great plug-in

I have configured the multi-branch plug-in with my Stash Git repository with the following relevant parameters:

* Sync Branches Schedule: H/5 * * * *
* [x] Allow anonymous trigger of branch sync
* Git
* Include Branches  *  (a * wildcard)
* Exclude Branches  <empty>

I have configured Stash Git to trigger Jenkins every time a push is made to the repository, and it works. However, when the branch name contains a forward slash, such as "feature/new-cool-feature", the hook is ignored and the branch is not built. If I click the "Schedule Build", the build is scheduled and runs fine. So it is just the trigger that it is not working.

I have read the plug-in has some issues with / in the names, but the issues described don't seem to match what is happening to us. My one and oly problem is the trigger coming from Stash being ignored.

Does anybody know of a workaround?

Thanks!
/jpeletier

**Comment by PilarJ** [comment]
I have the same problem.

When I push to branch test/test, in jenkins log I see trigger is called, but can't find the right branch. By matching projects I think it's comparing with escaped project name. In matching project names is : Project/test%2Ftest and then in log is "no project references the given repo url and commit branch"

**Comment by PilarJ** [comment]
release please. Have the same problem

**Comment by mjdetullio** [comment]
Related to #80

**Comment by mjdetullio** [comment]
Working on implementing the Branch API, which should handle hooks better

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32235
