### ISSUE TITLE
Use branch-api

### ISSUE THREAD

**Issue by jglick** [jenkinsci-transfer/multi-branch-project-plugin#120]
https://github.com/mjdetullio/multi-branch-project-plugin/blob/master/README.md#why-not-use-the-branch-api-plugin

It is 1.0 and there has been a great deal of work on it recently. Used from _Workflow: Multibranch_, _Literate_, and _YAML Project_.

**Comment by jglick** [comment]
(CC @stephenc)

https://github.com/jenkinsci/freestyle-multibranch-plugin works AFAIK.

**Comment by mjdetullio** [comment]
Awhile back I did notice some progress on it when I was looking into Workflow.  Good to see that it's 1.0.  Looks like I may have to revisit it again soon.  I'm mostly concerned about upgrade path for this plugin or whether or not it would make sense to deprecate it.

**Comment by mjdetullio** [comment]
I think it would be best to deprecate this plugin in the long run.  However, there's no suitable replacement for Maven Multi-Branch Projects under development in ```maven-plugin```.  Workflow would be a good substitute but I could see users wanting to hang on to the classic Maven job configs.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32234
