### ISSUE TITLE
Warnings Plugin not Configurable for Branch

### ISSUE THREAD

**Issue by jwernerny** [jenkinsci-transfer/multi-branch-project-plugin#126]
The Warnings Plugin (https://wiki.jenkins-ci.org/display/JENKINS/Warnings+Plugin) is not configurable through the GUI (web interface) for Branches.  When you go to add a console or workspace file log parser, it presents an empty drop down list instead of a list of parsers.

A workaround is manually editing template/config.xml.

**Comment by mjdetullio** [comment]
My guess is that it's Jelly files (or tag/s used in those files) are not compatible with https://github.com/jenkinsci/jenkins/blob/e2dccc35572b64f5e602a6b1b3efb517c578872c/core/src/main/resources/lib/form/withCustomDescriptorByName.jelly that is used by this plugin.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32233
