### ISSUE TITLE
Want an option to encode slashes in branch names differently

### ISSUE THREAD

**Issue by kazssym** [jenkinsci-transfer/multi-branch-project-plugin#15]
As issue #11 wrote, slashes in branch names are currently stored as %2F on the file system, but some application containers (I use GlassFish) do not like it in a URL. So I request an enhancement to add an option to encode slashes (or other special characters) differently, such as replacing with safe characters like '_' or something like that.

**Comment by fezfez** [comment]
+1

I have a Soap unit test in php with a local wsdl.

The result is "SOAP-ERROR: Parsing WSDL: Couldn't load from...."

**Comment by acuthbert** [comment]
Hi guys - I had this problem which affected my build steps in PHP as it couldn't handle paths with %2F in it. I made a fork of the plugin here:

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32253
