### ISSUE TITLE
Branch sync should wait for build to finish before deleting

### ISSUE THREAD

**Issue by unklphil** [jenkinsci-transfer/multi-branch-project-plugin#28]
Possibly related to #25 

Our test suite creates a test database that is normally removed after tests are done, however when the branch is deleted before the tests finish, the branch sync immediately deletes everything and the tests stop. This causes the test databases to not be deleted.

A possible solution would be to not delete a branch's job if it is currently building.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32251
