### ISSUE TITLE
Being able to edit project view as a fully dashboard view

### ISSUE THREAD

**Issue by Nodashi** [jenkinsci-transfer/multi-branch-project-plugin#30]
Being able to edit project view as a fully dashboard view

**Comment by mjdetullio** [comment]
The project list views are editable just like the standard views.  However, integration with the Dashboard plugin or other views is not exactly a high priority.  I'll accept pull requests.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32250
