### ISSUE TITLE
Incorrect link inside mutlijob phase inside a view

### ISSUE THREAD

**Issue by scaytrase** [jenkinsci-transfer/multi-branch-project-plugin#46]
If one branch of multibranch project is used as a single phase of multijob project, multijob dashboard display incorrect link (and possibly name?) to multibranch subproject.

I.e. given we have a view `TestView` and Multibranch project branch `MBTest > master` if we add this as a phase job to multijob project `Pipeline`, we will se a link to `TestView/branch/master` instead of correct link to `MBTest/branch/master` or so

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32249
