### ISSUE TITLE
Possible Features/Configs

### ISSUE THREAD

**Issue by lwhiteley** [jenkinsci-transfer/multi-branch-project-plugin#5]
Features/Options that could be in future implementations:

##### 1. Bi-Directional Sync of branches and jobs
This would mean that if a developer deletes a branch then the jenkins job  will be deleted as well. The same would happen if a job is deleted, then the corresponding git branch would be deleted remotely as well. This would be optional based on the workflow of  a team. 

Suggested options would be:
- Deleting branch triggers delete of job (One-Directional)
- Deleting job triggers delete of branch (One-Directional)
- Bi-Directional Delete 

##### 2. Delete Stale Jobs
This would be the ability to delete/cleanup jobs that are considered `stale` by some logic. This may be if it was last run at a configurable amount of time (Days/Weeks?).

##### 3. Smart Creation of jobs
With the plugins/tools available, they will recreate a job after it is deleted even if the user did not push to the branch. The plugin should be smart enough to only recreate a job if the user pushed to the branch since the last sync cycle. This would help with not creating jobs that are `stale` but still needed to be picked up at a later date for development/building.

***Note:***
Features 2 and 3 may need to use the webhook instead of polling to not use up a lot of resources. (May be a good idea to allow folks to choose polling or webhook for all functionality though. Would be interesting). This will ensure only branches with changes are created and built. 

##### 4. Sub Configs for Each branch

This would mostly be overrides, like always keep this branch so that it is never deleted. Use case would be to keep artifacts etc.
Another use case would be to add Build or Post-Build steps to a specific branch somehow for doing deploys as an example.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32256
