### ISSUE TITLE
Is it absolutely necessary to keep full .git repository in the sub-projects?

### ISSUE THREAD

**Issue by IvanAnishchuk** [jenkinsci-transfer/multi-branch-project-plugin#74]
Can't we use, say, just one git directory for all of them? (Making them multiple working directories for a single git repository.) It would save a lot of disk space and internet traffic.

At the very least, maybe we can use master-project's cloned repository as a remote for sub-projects? Local git clone uses hardlinks so the disk space and traffic would be preserved without changing how it looks inside each workdir.

[More info on SO](http://stackoverflow.com/questions/6270193/multiple-working-directories-with-git)

**Comment by mjdetullio** [comment]
If you used another local repository as the remote, a basic fetch wouldn't get the latest changes from the real remote.  The Jenkins polling mechanism would be broken.

Using multiple working directories is a good concept but simply far outside the design of the Jenkins SCM APIs and this plugin.

There are other things you can do to combat disk space usage like the Workspace Cleanup Plugin or setting a custom workspace to use the same location for all sub-projects (and then block their concurrency so they don't run at the same time).

**Comment by IvanAnishchuk** [comment]
Well, simplicity is important too, but still isn't it weird to have a dozen or more copies of exactly the same structure with exactly the same files, that are never going to be overridden or cause become desynchronized? I'd appreciate if there were some simple and reliable way to avoid wasting space for copies of git directories which are usually big and not actually that important anyway.

Maybe "shared" repositories is the way to go then? (See [git-clone manual](https://www.kernel.org/pub/software/scm/git/docs/git-clone.html)) — they don't have real data in them and are just linked to another repository so if you replace the remote with the real one after such cloning, they will get the latest change and put into the shared objects directory thus saving fetching time for other branches while appearing as if they were real repositories.

Such feature might require some low-level stuff in the Git plugin but would be really nice to have. As a precaution it can be added as optional to disable in case it causes any issues.

**Comment by johndefault** [comment]
Using reference git repository (together with shallow clone) can save space too. Would require just allowing advanced option already built into GIT plugin (nothing new, no low level stuff):
Source Code Management -> GIT -> Additional Behaviours -> Advanced clone behaviours -> Path of the reference repo to use during clone
Yes the reference repository needs to be synced regularly by another job.
BTW great plugin, could save lots of custom scripting to lots of people if the the repo disk space could be spared

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32246
