### ISSUE TITLE
Git publisher support

### ISSUE THREAD

**Issue by kubajanda** [jenkinsci-transfer/multi-branch-project-plugin#75]
I was trying to configure git publisher as post-build action, but I can't as there is no option to set repository name under SCM and then specify it as Target remote name in git publisher. 

Also the git publisher complains about Project not currently configured to use Git; cannot check remote repository.

Would it be possible to add git publisher support?

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32245
