### ISSUE TITLE
Environment variable for current branch

### ISSUE THREAD

**Issue by misery** [jenkinsci-transfer/multi-branch-project-plugin#77]
I need to know the current branch in generated job (see conditional step) but there is no $BRANCH variable or something like this I can use. $JOB_NAME does not contain only "branch name".

Please add a $CURRENT_BRANCH or something like this.
As a work-around I used Envinject plugin with the following groovy script.

```
def jobName = currentJob.getName()
return [BRANCH: "${jobName}"]
```
It's weird that currentJob.getName() works instead of $JOB_NAME.

**Comment by mjdetullio** [comment]
For Git there's GIT_BRANCH and probably similar for other SCMs

**Comment by misery** [comment]
Mercurial plugin provide MERCURIAL_REVISION_BRANCH for "non branch" builds only.

**Comment by mjdetullio** [comment]
Yes, I see now here https://github.com/jenkinsci/mercurial-plugin/blob/mercurial-1.54/src/main/java/hudson/plugins/mercurial/MercurialSCM.java#L851-852

Very odd...

Anyway I would recommend using the EnvInject plugin and adding this under the "Evaluated Groovy script" field:

```return [CURRENT_BRANCH: currentJob.scm.revision]```

I'll leave this open as an enhancement request

**Comment by bmerry** [comment]
I don't know if it is feasible, but it would also be nice if a $BRANCH (or whatever it is called) could be expanded by this plugin when generating the per-branch configuration from the template. That way it could be used in places where one can't ordinarily use $GIT_BRANCH. For example, it could appear in an upstream dependency, to support the type of workflow requested in [#114](https://github.com/mjdetullio/multi-branch-project-plugin/issues/114#issuecomment-149835415).

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32244
