### ISSUE TITLE
Parameterization of "Restrict where this project can be run"

### ISSUE THREAD

**Issue by misery** [jenkinsci-transfer/multi-branch-project-plugin#78]
We have some jobs than can be merged into one "multi branch" job. The only reason is that they need to run on another slave if it is branch "A" or branch "B". As this cannot be evaluated if the job started it needs to be "hardcoded" to the job configuration.

Idea:
Write in "global" job in "Restrict where this project can be run" field for example "Windows7_\$SUBJOB_BRANCH" and it will be "Windows7_stable" and "Windows7_master" in the sub projects.

**Comment by mjdetullio** [comment]
Historically, I don't think that field has ever accepted parameters.  I don't see why you'd want to have the same exact configuration for multiple branches of a project but still tie the branch to a single slave.

It's better practice to have multiple slaves under one label and have your slaves configured in a way that they are able to run builds for all your branches.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32243
