### ISSUE TITLE
Multi-branch multi-configuration projects

### ISSUE THREAD

**Issue by DerekDally** [jenkinsci-transfer/multi-branch-project-plugin#8]
Is there a way to define several configurations (common across all branches)?  If not, would it be difficult to implement?

Nice job with the plugin so far, it looks like it's going to make things a lot cleaner for this use case.

**Comment by osechet** [comment]
Any news about the implementation of this feature?

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32255
