### ISSUE TITLE
push to scm triggering respective jenkins job

### ISSUE THREAD

**Issue by kibotu** [jenkinsci-transfer/multi-branch-project-plugin#80]
As a developer
when I to push to a specific branch on github/gitlab 
then the scm should trigger the respective jenkins job
so that jenkins actually builds the branch with changes.

I tried JENKINS_URL/job/JOB_NAME/branch/BRANCH_NAME/build which only builds the scm default branch regardless to what branch has been pushed

i tried JENKINS_URL/git/notifyCommit?url=GIT_URL where however gitlab didn't trigger any build whatsoever

how can i achieve this? thanks.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32242
