### ISSUE TITLE
new config history created on each build

### ISSUE THREAD

**Issue by zowers** [jenkinsci-transfer/multi-branch-project-plugin#88]
we have JobConfigHistory plugin installed
https://wiki.jenkins-ci.org/display/JENKINS/JobConfigHistory+Plugin
and every build of each multibranch project makes the jobconfighistory to save new configuration in the history
though there are no changes in the config

**Comment by zowers** [comment]
also created issue in jobconfighistory-plugin tracker https://issues.jenkins-ci.org/browse/JENKINS-30089

**Comment by mjdetullio** [comment]
Using Jenkins JIRA issue
