### ISSUE TITLE
No test results in Maven multi-branch project

### ISSUE THREAD

**Issue by dcendents** [jenkinsci-transfer/multi-branch-project-plugin#93]
I created a Maven multi-branch project and I noticed that many of my branch builds did not record the junit test results, which seemed random. One build would work and the next would not.

I found the problem: when a maven project branch builds "unhindered" then it works normally, however if the "master" project scans for branches  and sync the config to the branch projects while a build is in progress, then the junit reporter will not work and it will record 0 junit tests. I find this alarming as the build will pass even if one of my tests fails (should be unstable).

It does not sound safe to systematically push (sync) the configuration to existing branches every time the master project scans the SCM. A perfect solution would be to delay the scan or the sync until all branch projects have finished building. An alternative solution could be to stop syncing the job config every time the project scans for branches and only do it when the master project configuration is modified, which comes down to the user to make sure he is not modifying the configuration while a branch project is building.

Great project by the way, I've been using the lterate plugin for a while but I like that your plugin lets me create "real" jenkins projects with all the available options. 

Thanks

**Comment by mjdetullio** [comment]
I haven't had a chance to test, but 0.4 uses a slightly different way of updating the configs which might now be safe.  If you can confirm the problem still exists I'll look into it some more.

**Comment by dcendents** [comment]
Yes and it seems even worse.

With version 0.3, the build passed but no test result was recorded. 

Now with version 0.4.1, it seems to stop the current build which shows as failed. But although a new build is started, the old one seems to run in the background, eventually finishes and then the build might show as passed. Sometimes it stays as failed although the console says it passed.

I know it sound confusing but it is. I had some build showed as failed an a new one staring, But worse it looks like it might fail a build on top of not recording test results.

**Comment by mjdetullio** [comment]
Moving to https://issues.jenkins-ci.org/browse/JENKINS-32240
